// AUTO-GENERATED by scripts/build-wgsl.mjs. Do not edit manually.
export type WgslVariant = 'hq' | 'lq' | 'tileable' | 'debug';

export const WGSL_VARIANTS: Record<WgslVariant, string> = {
  hq: `const WGSL_PLUS_DEBUG_ATOMS: bool = false;

fn wmod(x: f32, y: f32) -> f32 { return x - y * floor(x / y); }
fn wmod2(x: vec2f, y: f32) -> vec2f { return x - y * floor(x / y); }
fn wmod2v(x: vec2f, y: vec2f) -> vec2f { return x - y * floor(x / y); }

// Example atom helpers for WGSL-Plus modular linking.
fn ag_fade1(t: f32) -> f32 { return t * t * t * (t * (t * 6.0 - 15.0) + 10.0); }
fn ag_fade2(t: vec2f) -> vec2f { return vec2f(ag_fade1(t.x), ag_fade1(t.y)); }

const WGSL_PLUS_DEBUG_NOISE: bool = false;

fn hash2(p_in: vec2f) -> f32 {
  var p = fract(p_in * vec2f(234.345, 435.678));
  p += dot(p, p + 34.23);
  return fract(p.x * p.y);
}

fn hash22(p: vec2f) -> vec2f {
  let d = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return -1.0 + 2.0 * fract(sin(d) * 43758.5453123);
}

fn vnoise(p_in: vec2f, per: f32, tile: bool) -> f32 {
  let i = floor(p_in);
  let f = fract(p_in);
  let u = f * f * (3.0 - 2.0 * f);
  let tileMode = tile || false;
  var i00 = i;
  var i10 = i + vec2f(1.0, 0.0);
  var i01 = i + vec2f(0.0, 1.0);
  var i11 = i + vec2f(1.0, 1.0);
  if (tileMode) {
    i00 = wmod2(i00, per);
    i10 = wmod2(i10, per);
    i01 = wmod2(i01, per);
    i11 = wmod2(i11, per);
  }
  return mix(mix(hash2(i00), hash2(i10), u.x), mix(hash2(i01), hash2(i11), u.x), u.y);
}

fn fbm(p_in: vec2f, oct: f32, per_in: f32, tileFlag: f32) -> f32 {
  var p = p_in;
  var per = per_in;
  var v: f32 = 0.0;
  var a: f32 = 0.5;
  var mx: f32 = 0.0;
  let tile = (tileFlag > 0.5) || false;
  for (var i: i32 = 0; i < 8; i++) {
    let m = select(0.0, 1.0, f32(i) + 0.5 <= oct);
    v += a * vnoise(p, per, tile) * m;
    mx += a * m;
    p *= 2.0;
    per *= 2.0;
    a *= 0.5;
  }
  return select(0.0, v / mx, mx > 0.0);
}

fn voro(p_in: vec2f, jt: f32, per: f32, tile: bool) -> vec4f {
  var n = floor(p_in);
  let f = fract(p_in);
  let tileMode = tile || false;
  if (tileMode) {
    n = wmod2(n, per);
  }
  var f1: f32 = 8.0;
  var f2: f32 = 8.0;
  var id = vec2f(0.0);
  for (var j: i32 = -1; j <= 1; j++) {
    for (var i: i32 = -1; i <= 1; i++) {
      let g = vec2f(f32(i), f32(j));
      var neighbor = n + g;
      if (tileMode) {
        neighbor = wmod2(neighbor, per);
      }
      let o = hash22(neighbor);
      let r = g + o * jt - f;
      let d = dot(r, r);
      if (d < f1) {
        f2 = f1;
        f1 = d;
        id = o;
      } else if (d < f2) {
        f2 = d;
      }
    }
  }
  return vec4f(sqrt(f1), sqrt(f2), sqrt(f2) - sqrt(f1), id.x);
}

const WGSL_PLUS_DEBUG_SDF: bool = false;

fn sdCircle(p: vec2f, r: f32) -> f32 { return length(p) - r; }

fn sdBox(p: vec2f, b: vec2f) -> f32 {
  let d = abs(p) - b;
  return length(max(d, vec2f(0.0))) + min(max(d.x, d.y), 0.0);
}

fn sdEquilateralTriangle(p_in: vec2f, r: f32) -> f32 {
  let k = sqrt(3.0);
  var p = p_in;
  p.x = abs(p.x) - r;
  p.y = p.y + r / k;
  if (p.x + k * p.y > 0.0) {
    p = vec2f(p.x - k * p.y, -k * p.x - p.y) / 2.0;
  }
  p.x -= clamp(p.x, -2.0 * r, 0.0);
  return -length(p) * sign(p.y);
}

fn sdPolygon(p_in: vec2f, r: f32, n: i32) -> f32 {
  let an = 3.141593 / f32(n);
  let bn = wmod(atan2(p_in.x, p_in.y), 2.0 * an) - an;
  var p = length(p_in) * vec2f(cos(bn), abs(sin(bn)));
  p -= r * vec2f(cos(an), sin(an));
  p.y += clamp(-p.y, 0.0, r * tan(an));
  return length(p) * sign(p.x);
}

fn sdStar(p_in: vec2f, r: f32, n: i32, m: f32) -> f32 {
  let an = 3.141593 / f32(n);
  let en = 3.141593 / m;
  let acs = vec2f(cos(an), sin(an));
  let ecs = vec2f(cos(en), sin(en));
  let bn = wmod(atan2(p_in.x, p_in.y), 2.0 * an) - an;
  var p = length(p_in) * vec2f(cos(bn), abs(sin(bn)));
  p -= r * acs;
  p += ecs * clamp(-dot(p, ecs), 0.0, r * acs.y / ecs.y);
  return length(p) * sign(p.x);
}

const WGSL_PLUS_DEBUG_KERNELS: bool = false;

fn ag_node_grayscale(rgb: vec3f) -> f32 {
  return dot(rgb, vec3f(0.299, 0.587, 0.114));
}

fn ag_node_levels(v: f32, inLow: f32, inHigh: f32) -> f32 {
  let span = max(inHigh - inLow, 1e-5);
  return clamp((v - inLow) / span, 0.0, 1.0);
}

fn ag_node_blend(base: f32, layer: f32, opacity: f32) -> f32 {
  let t = clamp(opacity, 0.0, 1.0);
  return mix(base, layer, t);
}`,
  lq: `const WGSL_PLUS_DEBUG_ATOMS: bool = false;

fn wmod(x: f32, y: f32) -> f32 { return x - y * floor(x / y); }
fn wmod2(x: vec2f, y: f32) -> vec2f { return x - y * floor(x / y); }
fn wmod2v(x: vec2f, y: vec2f) -> vec2f { return x - y * floor(x / y); }

// Example atom helpers for WGSL-Plus modular linking.
fn ag_fade1(t: f32) -> f32 { return t * t * t * (t * (t * 6.0 - 15.0) + 10.0); }
fn ag_fade2(t: vec2f) -> vec2f { return vec2f(ag_fade1(t.x), ag_fade1(t.y)); }

const WGSL_PLUS_DEBUG_NOISE: bool = false;

fn hash2(p_in: vec2f) -> f32 {
  var p = fract(p_in * vec2f(234.345, 435.678));
  p += dot(p, p + 34.23);
  return fract(p.x * p.y);
}

fn hash22(p: vec2f) -> vec2f {
  let d = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return -1.0 + 2.0 * fract(sin(d) * 43758.5453123);
}

fn vnoise(p_in: vec2f, per: f32, tile: bool) -> f32 {
  let i = floor(p_in);
  let f = fract(p_in);
  let u = f * f * (3.0 - 2.0 * f);
  let tileMode = tile || false;
  var i00 = i;
  var i10 = i + vec2f(1.0, 0.0);
  var i01 = i + vec2f(0.0, 1.0);
  var i11 = i + vec2f(1.0, 1.0);
  if (tileMode) {
    i00 = wmod2(i00, per);
    i10 = wmod2(i10, per);
    i01 = wmod2(i01, per);
    i11 = wmod2(i11, per);
  }
  return mix(mix(hash2(i00), hash2(i10), u.x), mix(hash2(i01), hash2(i11), u.x), u.y);
}

fn fbm(p_in: vec2f, oct: f32, per_in: f32, tileFlag: f32) -> f32 {
  var p = p_in;
  var per = per_in;
  var v: f32 = 0.0;
  var a: f32 = 0.5;
  var mx: f32 = 0.0;
  let tile = (tileFlag > 0.5) || false;
  for (var i: i32 = 0; i < 5; i++) {
    let m = select(0.0, 1.0, f32(i) + 0.5 <= oct);
    v += a * vnoise(p, per, tile) * m;
    mx += a * m;
    p *= 2.0;
    per *= 2.0;
    a *= 0.5;
  }
  return select(0.0, v / mx, mx > 0.0);
}

fn voro(p_in: vec2f, jt: f32, per: f32, tile: bool) -> vec4f {
  var n = floor(p_in);
  let f = fract(p_in);
  let tileMode = tile || false;
  if (tileMode) {
    n = wmod2(n, per);
  }
  var f1: f32 = 8.0;
  var f2: f32 = 8.0;
  var id = vec2f(0.0);
  for (var j: i32 = -1; j <= 1; j++) {
    for (var i: i32 = -1; i <= 1; i++) {
      let g = vec2f(f32(i), f32(j));
      var neighbor = n + g;
      if (tileMode) {
        neighbor = wmod2(neighbor, per);
      }
      let o = hash22(neighbor);
      let r = g + o * jt - f;
      let d = dot(r, r);
      if (d < f1) {
        f2 = f1;
        f1 = d;
        id = o;
      } else if (d < f2) {
        f2 = d;
      }
    }
  }
  return vec4f(sqrt(f1), sqrt(f2), sqrt(f2) - sqrt(f1), id.x);
}

const WGSL_PLUS_DEBUG_SDF: bool = false;

fn sdCircle(p: vec2f, r: f32) -> f32 { return length(p) - r; }

fn sdBox(p: vec2f, b: vec2f) -> f32 {
  let d = abs(p) - b;
  return length(max(d, vec2f(0.0))) + min(max(d.x, d.y), 0.0);
}

fn sdEquilateralTriangle(p_in: vec2f, r: f32) -> f32 {
  let k = sqrt(3.0);
  var p = p_in;
  p.x = abs(p.x) - r;
  p.y = p.y + r / k;
  if (p.x + k * p.y > 0.0) {
    p = vec2f(p.x - k * p.y, -k * p.x - p.y) / 2.0;
  }
  p.x -= clamp(p.x, -2.0 * r, 0.0);
  return -length(p) * sign(p.y);
}

fn sdPolygon(p_in: vec2f, r: f32, n: i32) -> f32 {
  let an = 3.141593 / f32(n);
  let bn = wmod(atan2(p_in.x, p_in.y), 2.0 * an) - an;
  var p = length(p_in) * vec2f(cos(bn), abs(sin(bn)));
  p -= r * vec2f(cos(an), sin(an));
  p.y += clamp(-p.y, 0.0, r * tan(an));
  return length(p) * sign(p.x);
}

fn sdStar(p_in: vec2f, r: f32, n: i32, m: f32) -> f32 {
  let an = 3.141593 / f32(n);
  let en = 3.141593 / m;
  let acs = vec2f(cos(an), sin(an));
  let ecs = vec2f(cos(en), sin(en));
  let bn = wmod(atan2(p_in.x, p_in.y), 2.0 * an) - an;
  var p = length(p_in) * vec2f(cos(bn), abs(sin(bn)));
  p -= r * acs;
  p += ecs * clamp(-dot(p, ecs), 0.0, r * acs.y / ecs.y);
  return length(p) * sign(p.x);
}

const WGSL_PLUS_DEBUG_KERNELS: bool = false;

fn ag_node_grayscale(rgb: vec3f) -> f32 {
  return dot(rgb, vec3f(0.299, 0.587, 0.114));
}

fn ag_node_levels(v: f32, inLow: f32, inHigh: f32) -> f32 {
  let span = max(inHigh - inLow, 1e-5);
  return clamp((v - inLow) / span, 0.0, 1.0);
}

fn ag_node_blend(base: f32, layer: f32, opacity: f32) -> f32 {
  let t = clamp(opacity, 0.0, 1.0);
  return mix(base, layer, t);
}`,
  tileable: `const WGSL_PLUS_DEBUG_ATOMS: bool = false;

fn wmod(x: f32, y: f32) -> f32 { return x - y * floor(x / y); }
fn wmod2(x: vec2f, y: f32) -> vec2f { return x - y * floor(x / y); }
fn wmod2v(x: vec2f, y: vec2f) -> vec2f { return x - y * floor(x / y); }

// Example atom helpers for WGSL-Plus modular linking.
fn ag_fade1(t: f32) -> f32 { return t * t * t * (t * (t * 6.0 - 15.0) + 10.0); }
fn ag_fade2(t: vec2f) -> vec2f { return vec2f(ag_fade1(t.x), ag_fade1(t.y)); }

const WGSL_PLUS_DEBUG_NOISE: bool = false;

fn hash2(p_in: vec2f) -> f32 {
  var p = fract(p_in * vec2f(234.345, 435.678));
  p += dot(p, p + 34.23);
  return fract(p.x * p.y);
}

fn hash22(p: vec2f) -> vec2f {
  let d = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return -1.0 + 2.0 * fract(sin(d) * 43758.5453123);
}

fn vnoise(p_in: vec2f, per: f32, tile: bool) -> f32 {
  let i = floor(p_in);
  let f = fract(p_in);
  let u = f * f * (3.0 - 2.0 * f);
  let tileMode = tile || true;
  var i00 = i;
  var i10 = i + vec2f(1.0, 0.0);
  var i01 = i + vec2f(0.0, 1.0);
  var i11 = i + vec2f(1.0, 1.0);
  if (tileMode) {
    i00 = wmod2(i00, per);
    i10 = wmod2(i10, per);
    i01 = wmod2(i01, per);
    i11 = wmod2(i11, per);
  }
  return mix(mix(hash2(i00), hash2(i10), u.x), mix(hash2(i01), hash2(i11), u.x), u.y);
}

fn fbm(p_in: vec2f, oct: f32, per_in: f32, tileFlag: f32) -> f32 {
  var p = p_in;
  var per = per_in;
  var v: f32 = 0.0;
  var a: f32 = 0.5;
  var mx: f32 = 0.0;
  let tile = (tileFlag > 0.5) || true;
  for (var i: i32 = 0; i < 8; i++) {
    let m = select(0.0, 1.0, f32(i) + 0.5 <= oct);
    v += a * vnoise(p, per, tile) * m;
    mx += a * m;
    p *= 2.0;
    per *= 2.0;
    a *= 0.5;
  }
  return select(0.0, v / mx, mx > 0.0);
}

fn voro(p_in: vec2f, jt: f32, per: f32, tile: bool) -> vec4f {
  var n = floor(p_in);
  let f = fract(p_in);
  let tileMode = tile || true;
  if (tileMode) {
    n = wmod2(n, per);
  }
  var f1: f32 = 8.0;
  var f2: f32 = 8.0;
  var id = vec2f(0.0);
  for (var j: i32 = -1; j <= 1; j++) {
    for (var i: i32 = -1; i <= 1; i++) {
      let g = vec2f(f32(i), f32(j));
      var neighbor = n + g;
      if (tileMode) {
        neighbor = wmod2(neighbor, per);
      }
      let o = hash22(neighbor);
      let r = g + o * jt - f;
      let d = dot(r, r);
      if (d < f1) {
        f2 = f1;
        f1 = d;
        id = o;
      } else if (d < f2) {
        f2 = d;
      }
    }
  }
  return vec4f(sqrt(f1), sqrt(f2), sqrt(f2) - sqrt(f1), id.x);
}

const WGSL_PLUS_DEBUG_SDF: bool = false;

fn sdCircle(p: vec2f, r: f32) -> f32 { return length(p) - r; }

fn sdBox(p: vec2f, b: vec2f) -> f32 {
  let d = abs(p) - b;
  return length(max(d, vec2f(0.0))) + min(max(d.x, d.y), 0.0);
}

fn sdEquilateralTriangle(p_in: vec2f, r: f32) -> f32 {
  let k = sqrt(3.0);
  var p = p_in;
  p.x = abs(p.x) - r;
  p.y = p.y + r / k;
  if (p.x + k * p.y > 0.0) {
    p = vec2f(p.x - k * p.y, -k * p.x - p.y) / 2.0;
  }
  p.x -= clamp(p.x, -2.0 * r, 0.0);
  return -length(p) * sign(p.y);
}

fn sdPolygon(p_in: vec2f, r: f32, n: i32) -> f32 {
  let an = 3.141593 / f32(n);
  let bn = wmod(atan2(p_in.x, p_in.y), 2.0 * an) - an;
  var p = length(p_in) * vec2f(cos(bn), abs(sin(bn)));
  p -= r * vec2f(cos(an), sin(an));
  p.y += clamp(-p.y, 0.0, r * tan(an));
  return length(p) * sign(p.x);
}

fn sdStar(p_in: vec2f, r: f32, n: i32, m: f32) -> f32 {
  let an = 3.141593 / f32(n);
  let en = 3.141593 / m;
  let acs = vec2f(cos(an), sin(an));
  let ecs = vec2f(cos(en), sin(en));
  let bn = wmod(atan2(p_in.x, p_in.y), 2.0 * an) - an;
  var p = length(p_in) * vec2f(cos(bn), abs(sin(bn)));
  p -= r * acs;
  p += ecs * clamp(-dot(p, ecs), 0.0, r * acs.y / ecs.y);
  return length(p) * sign(p.x);
}

const WGSL_PLUS_DEBUG_KERNELS: bool = false;

fn ag_node_grayscale(rgb: vec3f) -> f32 {
  return dot(rgb, vec3f(0.299, 0.587, 0.114));
}

fn ag_node_levels(v: f32, inLow: f32, inHigh: f32) -> f32 {
  let span = max(inHigh - inLow, 1e-5);
  return clamp((v - inLow) / span, 0.0, 1.0);
}

fn ag_node_blend(base: f32, layer: f32, opacity: f32) -> f32 {
  let t = clamp(opacity, 0.0, 1.0);
  return mix(base, layer, t);
}`,
  debug: `const WGSL_PLUS_DEBUG_ATOMS: bool = true;

fn wmod(x: f32, y: f32) -> f32 { return x - y * floor(x / y); }
fn wmod2(x: vec2f, y: f32) -> vec2f { return x - y * floor(x / y); }
fn wmod2v(x: vec2f, y: vec2f) -> vec2f { return x - y * floor(x / y); }

// Example atom helpers for WGSL-Plus modular linking.
fn ag_fade1(t: f32) -> f32 { return t * t * t * (t * (t * 6.0 - 15.0) + 10.0); }
fn ag_fade2(t: vec2f) -> vec2f { return vec2f(ag_fade1(t.x), ag_fade1(t.y)); }

const WGSL_PLUS_DEBUG_NOISE: bool = true;

fn hash2(p_in: vec2f) -> f32 {
  var p = fract(p_in * vec2f(234.345, 435.678));
  p += dot(p, p + 34.23);
  return fract(p.x * p.y);
}

fn hash22(p: vec2f) -> vec2f {
  let d = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return -1.0 + 2.0 * fract(sin(d) * 43758.5453123);
}

fn vnoise(p_in: vec2f, per: f32, tile: bool) -> f32 {
  let i = floor(p_in);
  let f = fract(p_in);
  let u = f * f * (3.0 - 2.0 * f);
  let tileMode = tile || false;
  var i00 = i;
  var i10 = i + vec2f(1.0, 0.0);
  var i01 = i + vec2f(0.0, 1.0);
  var i11 = i + vec2f(1.0, 1.0);
  if (tileMode) {
    i00 = wmod2(i00, per);
    i10 = wmod2(i10, per);
    i01 = wmod2(i01, per);
    i11 = wmod2(i11, per);
  }
  return mix(mix(hash2(i00), hash2(i10), u.x), mix(hash2(i01), hash2(i11), u.x), u.y);
}

fn fbm(p_in: vec2f, oct: f32, per_in: f32, tileFlag: f32) -> f32 {
  var p = p_in;
  var per = per_in;
  var v: f32 = 0.0;
  var a: f32 = 0.5;
  var mx: f32 = 0.0;
  let tile = (tileFlag > 0.5) || false;
  for (var i: i32 = 0; i < 8; i++) {
    let m = select(0.0, 1.0, f32(i) + 0.5 <= oct);
    v += a * vnoise(p, per, tile) * m;
    mx += a * m;
    p *= 2.0;
    per *= 2.0;
    a *= 0.5;
  }
  return select(0.0, v / mx, mx > 0.0);
}

fn voro(p_in: vec2f, jt: f32, per: f32, tile: bool) -> vec4f {
  var n = floor(p_in);
  let f = fract(p_in);
  let tileMode = tile || false;
  if (tileMode) {
    n = wmod2(n, per);
  }
  var f1: f32 = 8.0;
  var f2: f32 = 8.0;
  var id = vec2f(0.0);
  for (var j: i32 = -1; j <= 1; j++) {
    for (var i: i32 = -1; i <= 1; i++) {
      let g = vec2f(f32(i), f32(j));
      var neighbor = n + g;
      if (tileMode) {
        neighbor = wmod2(neighbor, per);
      }
      let o = hash22(neighbor);
      let r = g + o * jt - f;
      let d = dot(r, r);
      if (d < f1) {
        f2 = f1;
        f1 = d;
        id = o;
      } else if (d < f2) {
        f2 = d;
      }
    }
  }
  return vec4f(sqrt(f1), sqrt(f2), sqrt(f2) - sqrt(f1), id.x);
}

const WGSL_PLUS_DEBUG_SDF: bool = true;

fn sdCircle(p: vec2f, r: f32) -> f32 { return length(p) - r; }

fn sdBox(p: vec2f, b: vec2f) -> f32 {
  let d = abs(p) - b;
  return length(max(d, vec2f(0.0))) + min(max(d.x, d.y), 0.0);
}

fn sdEquilateralTriangle(p_in: vec2f, r: f32) -> f32 {
  let k = sqrt(3.0);
  var p = p_in;
  p.x = abs(p.x) - r;
  p.y = p.y + r / k;
  if (p.x + k * p.y > 0.0) {
    p = vec2f(p.x - k * p.y, -k * p.x - p.y) / 2.0;
  }
  p.x -= clamp(p.x, -2.0 * r, 0.0);
  return -length(p) * sign(p.y);
}

fn sdPolygon(p_in: vec2f, r: f32, n: i32) -> f32 {
  let an = 3.141593 / f32(n);
  let bn = wmod(atan2(p_in.x, p_in.y), 2.0 * an) - an;
  var p = length(p_in) * vec2f(cos(bn), abs(sin(bn)));
  p -= r * vec2f(cos(an), sin(an));
  p.y += clamp(-p.y, 0.0, r * tan(an));
  return length(p) * sign(p.x);
}

fn sdStar(p_in: vec2f, r: f32, n: i32, m: f32) -> f32 {
  let an = 3.141593 / f32(n);
  let en = 3.141593 / m;
  let acs = vec2f(cos(an), sin(an));
  let ecs = vec2f(cos(en), sin(en));
  let bn = wmod(atan2(p_in.x, p_in.y), 2.0 * an) - an;
  var p = length(p_in) * vec2f(cos(bn), abs(sin(bn)));
  p -= r * acs;
  p += ecs * clamp(-dot(p, ecs), 0.0, r * acs.y / ecs.y);
  return length(p) * sign(p.x);
}

const WGSL_PLUS_DEBUG_KERNELS: bool = true;

fn ag_node_grayscale(rgb: vec3f) -> f32 {
  return dot(rgb, vec3f(0.299, 0.587, 0.114));
}

fn ag_node_levels(v: f32, inLow: f32, inHigh: f32) -> f32 {
  let span = max(inHigh - inLow, 1e-5);
  return clamp((v - inLow) / span, 0.0, 1.0);
}

fn ag_node_blend(base: f32, layer: f32, opacity: f32) -> f32 {
  let t = clamp(opacity, 0.0, 1.0);
  return mix(base, layer, t);
}`,
};

export function getCompiledWgsl(variant: WgslVariant = 'hq'): string {
  return WGSL_VARIANTS[variant];
}

export const WGSL_COMPILED = WGSL_VARIANTS.hq;

export default WGSL_COMPILED;
