import { spawnSync } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const shaderDir = path.join(rootDir, 'src', 'shaders');
const generatedDir = path.join(shaderDir, '.generated');
const mainPath = path.join(shaderDir, 'main.wgsl');
const cliPath = path.join(rootDir, 'node_modules', 'wgsl-plus', 'dist', 'cli.js');
const compiledWgslPath = path.join(shaderDir, 'compiled.wgsl');
const compiledTsPath = path.join(shaderDir, 'compiled.ts');

const variants = [
  { id: 'hq', defines: ['HQ'] },
  { id: 'lq', defines: ['LQ'] },
  { id: 'tileable', defines: ['HQ', 'TILEABLE'] },
  { id: 'debug', defines: ['HQ', 'DEBUG'] },
];

function escapeTemplateLiteral(input) {
  return input.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

async function ensureInputs() {
  await fs.access(mainPath);
  await fs.access(cliPath);
}

async function compileVariant(variant) {
  const wrapperPath = path.join(generatedDir, `variant-${variant.id}.wgsl`);
  const outputPath = path.join(generatedDir, `variant-${variant.id}.out.wgsl`);
  const defineLines = variant.defines.map((token) => `#define ${token} 1`).join('\n');
  const wrapperSource = `${defineLines}\n#include "../main.wgsl"\n`;
  await fs.writeFile(wrapperPath, wrapperSource, 'utf8');

  const run = spawnSync(process.execPath, [cliPath, wrapperPath, '-o', outputPath], {
    cwd: rootDir,
    encoding: 'utf8',
  });
  if (run.status !== 0) {
    throw new Error(`wgsl-plus failed for variant "${variant.id}":\n${run.stderr || run.stdout || 'Unknown error'}`);
  }
  return (await fs.readFile(outputPath, 'utf8')).trim();
}

async function writeCompiledTs(outputs) {
  const variantType = variants.map((v) => `'${v.id}'`).join(' | ');
  const variantEntries = variants
    .map((v) => `  ${v.id}: \`${escapeTemplateLiteral(outputs[v.id])}\`,`)
    .join('\n');

  const fileSource = `// AUTO-GENERATED by scripts/build-wgsl.mjs. Do not edit manually.
export type WgslVariant = ${variantType};

export const WGSL_VARIANTS: Record<WgslVariant, string> = {
${variantEntries}
};

export function getCompiledWgsl(variant: WgslVariant = 'hq'): string {
  return WGSL_VARIANTS[variant];
}

export const WGSL_COMPILED = WGSL_VARIANTS.hq;

export default WGSL_COMPILED;
`;

  await fs.writeFile(compiledTsPath, fileSource, 'utf8');
}

async function main() {
  await ensureInputs();
  await fs.mkdir(generatedDir, { recursive: true });
  const outputs = {};
  for (const variant of variants) {
    outputs[variant.id] = await compileVariant(variant);
  }
  await fs.writeFile(compiledWgslPath, `${outputs.hq}\n`, 'utf8');
  await writeCompiledTs(outputs);
  await fs.rm(generatedDir, { recursive: true, force: true });
  console.log('[wgsl] Compiled variants:', variants.map((v) => v.id).join(', '));
}

main().catch(async (error) => {
  try {
    await fs.rm(generatedDir, { recursive: true, force: true });
  } catch {
    // ignore cleanup errors
  }
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
